### ISSUE TITLE
[회원가입]

### ISSUE THREAD

**Issue by hek316** [f-lab-edu/mars#3]
### 1. 사용자 테이블 설계
- **설명**: 사용자 기본 정보 (이메일, 비밀번호 등) 및 거래 내역을 저장할 테이블 설계.
- **작업 항목**:
  - 사용자 기본 정보와 관련된 테이블 설계.
  - 이메일, 비밀번호 등의 필드를 저장하는 테이블 설계.

### 2. 사용자 비밀번호 암호화 처리
- **설명**: 사용자 비밀번호를 안전하게 저장하기 위해 암호화 처리.
- **작업 항목**:
  - 비밀번호를 단방향 암호화 처리.

### 3. 회원가입 API 구현
- **설명**: 사용자가 회원가입을 할 수 있도록 API 구현.
- **작업 항목**:
  - 이메일, 비밀번호 등의 정보를 받아 회원가입 처리.
  - 회원가입 후 사용자 정보를 데이터베이스에 저장.

### 4. 사용자 데이터 유효성 검사
- **설명**: 사용자 정보 입력 시 유효성 검사 구현.
- **작업 항목**:
  - Spring Validation을 사용하여 이메일 포맷, 비밀번호 길이 등 유효성 검사.

### 5. 중복 이메일 검사
- **설명**: 이미 존재하는 이메일로 회원가입하지 않도록 중복 이메일 검사 구현.
- **작업 항목**:
  - 회원가입 시 이메일 중복 여부를 확인하는 로직 구현.

### 6. 회원가입 오류 처리
- **설명**: 회원가입 시 발생할 수 있는 예외 처리.
- **작업 항목**:
  - 이메일 형식이 잘못된 경우, 비밀번호가 불충분한 경우 등의 예외 처리.

### 7. 회원가입 성공 시 응답 처리
- **설명**: 회원가입 성공 시 사용자 정보를 반환하거나 로그인 처리.
- **작업 항목**:
 - 회원가입 성공 후 사용자 정보 또는 인증 토큰 반환.

### 8. 회원가입 기능 단위 테스트 구현
- **설명**: 회원가입 기능에 대한 단위 테스트 코드 작성.
- **작업 항목**:
  - **테스트 코드 작성**:
    - **회원가입 성공 테스트**: 유효한 이메일과 비밀번호로 회원가입이 성공적으로 처리되는지 테스트.
    - **이메일 중복 테스트**: 이미 존재하는 이메일로 회원가입을 시도할 때 적절한 오류가 발생하는지 테스트.
    - **유효성 검사 테스트**: 잘못된 이메일 포맷이나 비밀번호 규격을 가진 경우에 예외가 발생하는지 테스트.
    - **비밀번호 암호화 테스트**: 비밀번호가 암호화되어 데이터베이스에 저장되는지 확인하는 테스트.
    - **예외 처리 테스트**: 잘못된 입력 값에 대해 적절한 오류 메시지나 예외가 반환되는지 테스트.

**Comment by f-lab-cacio** [comment]
분류하신 단위 별로 개별 이슈로 생성하시죠! 
구별을 위해 이슈 이름에 `[회원가입]` 과 같은 구분자 넣어서 생성 하고 이 이슈의 코멘트에 링크 함께 달아두면 관리하기 용이할 것 같습니다

**Comment by hek316** [comment]
1. [사용자 테이블 설계](https://github.com/f-lab-edu/mars/issues/5)
2. [사용자 비밀번호 암호화 처리](https://github.com/f-lab-edu/mars/issues/6)
3. [회원가입 API 구현](https://github.com/f-lab-edu/mars/issues/7)
4. [사용자 데이터 유효성 검사](https://github.com/f-lab-edu/mars/issues/8)
5. [중복 이메일 검사](https://github.com/f-lab-edu/mars/issues/9)
6. [회원가입 오류 처리](https://github.com/f-lab-edu/mars/issues/10)
7. [회원가입 성공 시 응답 처리](https://github.com/f-lab-edu/mars/issues/11)
8. [회원가입 기능 단위 테스트 구현](https://github.com/f-lab-edu/mars/issues/12)

**Comment by hek316** [comment]
> 분류하신 단위 별로 개별 이슈로 생성하시죠! 구별을 위해 이슈 이름에 `[회원가입]` 과 같은 구분자 넣어서 생성 하고 이 이슈의 코멘트에 링크 함께 달아두면 관리하기 용이할 것 같습니다

넵 완료하였습니다!
